name: gs-reg
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.15
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - scipy
  - plyfile
  - tqdm
  - pip=25.0.1
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - submodules/fused-ssim
      - open3d
      - opencv-python
      - joblib
