name: gaussian_splatting
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.10.15
  - pip=25.0.1
  - scipy
  - tqdm
  - pip:
    - torch --extra-index-url https://download.pytorch.org/whl/cu118
    - torchvision --extra-index-url https://download.pytorch.org/whl/cu118
    - torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
